import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <header className="align-center flex grow-0 justify-between bg-blue-100 p-2">
            <h1 className="font-mono text-2xl font-bold">Lorem Ipsum</h1>

            <nav className="align-center flex gap-4">
              <a href="/">Home</a>
              <a href="/nested">Nested</a>
            </nav>
          </header>

          <main className="grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
